### ISSUE TITLE
dropping location issue

### ISSUE THREAD

**Issue by zorayang** [Cav19/Zoframenco#8]
To test the scoring, these happened 1) sometimes no red box appearing after picking up the passenger 2) red box appearing at places other than the parking lot 3) can touch on but not fully go through the red box to drop the passenger.

**Comment by fnutrica** [comment]
When this happened, had you changed the size of your screen? Toggled
fullscreen or just resided the window?

_Francesco Nutricato_
Economics preceptor
Lifeguard

_Macalester College_
1600 Grand Avenue, Saint Paul (MN)
francesconutricato@gmail.com
(651) 401-6399
LinkedIn account
https://www.linkedin.com/profile/view?id=221969772&authType=name&authToken=-Juw&goback=%2Epdf_221969772_*1_*2_name_*5Juw_FrancescoNutricato_true_*1

**Comment by zorayang** [comment]
I believe everything is default and I believe it's the same on Mengdie's
laptop

On Friday, April 22, 2016, Francesco Nutricato notifications@github.com
wrote:

> When this happened, had you changed the size of your screen? Toggled
> fullscreen or just resided the window?
> 
> _Francesco Nutricato_
> Economics preceptor
> Lifeguard
> 
> _Macalester College_
> 1600 Grand Avenue, Saint Paul (MN)
> francesconutricato@gmail.com
> <javascript:_e(%7B%7D,'cvml','francesconutricato@gmail.com');>
> (651) 401-6399
> LinkedIn account
> <
> https://www.linkedin.com/profile/view?id=221969772&authType=name&authToken=-Juw&goback=%2Epdf_221969772_*1_*2_name_*5Juw_FrancescoNutricato_true_*1
> 
> 
> On Thu, Apr 21, 2016 at 10:12 PM, Zora Yang <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > To test the scoring, these happened 1) sometimes no red box appearing
> > after picking up the passenger 2) red box appearing at places other than
> > the parking lot 3) can touch on but not fully go through the red box to
> > drop the passenger.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/Cav19/Zoframenco/issues/8
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Cav19/Zoframenco/issues/8#issuecomment-213429486

## 

Yezi Yang (Zora)
Applied Mathematics and Statistics | Computer Science | Economics
Macalester College '16

**Comment by fnutrica** [comment]
Ok, It`s working on my laptop so I am not sure what the issue is. Maybe
something with the resolution... Has it always/ever worked in the past?
I cannot meet today, as I will be at work.



*Francesco Nutricato*
Economics preceptor
Lifeguard

*Macalester College*
1600 Grand Avenue, Saint Paul (MN)
francesconutricato@gmail.com
(651) 401-6399
LinkedIn account
<https://www.linkedin.com/profile/view?id=221969772&authType=name&authToken=-Juw&goback=%2Epdf_221969772_*1_*2_name_*5Juw_FrancescoNutricato_true_*1>
